### ISSUE TITLE
Patch files are platform dependent

### ISSUE THREAD

**Issue by LexManos** [jamiemansfield/ProPatcher#11]
diff4j uses [System.getProperty("line.separator")](https://github.com/cloudbees/diff4j/blob/master/src/main/java/com/cloudbees/diff/UnifiedDiff.java#L72) for the new line characters in patch files. This is not ideal when submitting patches to a source repo.
Whenever you get a chance, adding a option to standardize the line endings would be useful.

**Comment by jamierocks** [comment]
Interesting, https://github.com/CadixDev/ProPatcher/commit/8ca6ec2e31b3ff3ff6967bb23a67cf4858eb13f9 should be resolving this.

**Comment by LexManos** [comment]
Indeed it does, sorry about this, Seems my update checker didn't see there was an update.
