### ISSUE TITLE
applyPatches is not applying any patchfiles under Linux

### ISSUE THREAD

**Issue by kingdevnl** [jamiemansfield/ProPatcher#8]
So it isn't applying any patchFiles under linux,
No errors produced either from the plugin...
https://github.com/kingdevnl/EML/blob/master/build.gradle

**Comment by jamierocks** [comment]
Huh, will take a look - though I'm sure @kashike has used it with MCPConfig

**Comment by kingdevnl** [comment]
@jamierocks I dynamic get the base source that i want to compare etc, It all works 100% fine on windows

**Comment by jamierocks** [comment]
I'm of the thought that the line normalisation may be at fault - though I have no means of testing anything on a Windows machine... :(

I will however, take a good look at your repo again - see if I can spot anything :)
